# Generated by Django 5.2.3 on 2025-06-30 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('guardian_name', models.CharField(max_length=128)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_graduated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.student')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
